### ISSUE TITLE
decord._ffi.base.DECORDError: [16:33:15] /github/workspace/src/video/video_reader.cc:486: Error: av_read_frame failed with 1094995529

### ISSUE THREAD

**Issue by pp-jia** [dmlc/decord#315]
在进行推理时，控制台decord包报错，请问如何解决？
![image](https://github.com/user-attachments/assets/9d25476f-eb9c-4996-915b-69e87e720313)

**Comment by hrlics** [comment]
> 在进行推理时，控制台decord包报错，请问如何解决？ ![image](https://github.com/user-attachments/assets/9d25476f-eb9c-4996-915b-69e87e720313)

请问解决了吗

**Comment by pp-jia** [comment]
> > 在进行推理时，控制台decord包报错，请问如何解决？ ![image](https://github.com/user-attachments/assets/9d25476f-eb9c-4996-915b-69e87e720313)
> 
> 请问解决了吗

我的视频文件损坏了，我通过ffmpeg修复我的视频文件解决的。
