### ISSUE TITLE
Fails to build with FFmpeg 8.0: error: no member named 'channels' in 'AVCodecParameters'

### ISSUE THREAD

**Issue by yurivict** [dmlc/decord#352]
[log](https://bz-attachments.freebsd.org/attachment.cgi?id=263168)
